### PR TITLE
Update covid03162020.cls

### PR DESCRIPTION
**Pull request by aruntiri**
Updated the ImportFromStream method

### CODE REVIEW

**Comment by evshvarov** [comment]
$p won’t work because of “Korea, South”

Need it to be processed via parser.
We can try to save to %File.TempFileName and then import via Import()

**Comment by aruntiri** [comment]
Would it help if we change the "," in the “Korea, South” to ";" and then remove the " as a whole from the line. In that way we can ignore this exception case as a whole? I hadn't had this issue until last week, so did not need to handle it.

**Comment by aruntiri** [comment]
I will send another pull request. We don't need to worry about a " any longer.

2020-04-08 10_41_43-SQL

**Comment by aruntiri** [comment]
updated

**Comment by evshvarov** [comment]
:) It's a trick but this will work here ) Merged

**Pull request merged**
